// <auto-generated>
// Antigravity IDE — Unity analyzer suppressions
// This file suppresses false-positive diagnostics for Unity API messages.
// Safe to delete if not using Roslyn analyzers.
// </auto-generated>

using System.Diagnostics.CodeAnalysis;

// Suppress warnings for Unity message methods that appear unused to static analysis
[assembly: SuppressMessage("CodeQuality", "IDE0051:Remove unused private members",
    Justification = "Unity message methods are called by the engine via reflection")]
